import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "@/components/NavBar.component";
import Provider from "@/trpc/Provider";
import 'react-loading-skeleton/dist/skeleton.css'
import {Toaster} from '@/components/ui/toaster';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <Provider>
        <body
          className={cn(
            "min-h-screen font-sans antialiased rounded grainy",
            inter.className
          )}
        >
          <Toaster/>
          <NavBar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
