export const PLANS = [
    {
        name:'Free',
        slug:'free',
        quota:10,
        pagePerPdf:5,
        price:{
            amount:0,
            priceIds:{
                test:'',
                production:''
            }
        }
    },
    {
        name:'Pro',
        slug:'pro',
        quota:50,
        pagePerPdf:25,
        price:{
            amount:1400,
            priceIds:{
                test:'price_1OzxgiSJxnfgBiBpn7zBayE4',
                production:''
            }
        }
    }
]